<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 5 Detección de Puntos de Cambio | EUR/USD</title>
<meta name="author" content="Harvey Bastidas, Andrés Caicedo, Alexander Alvarado">
<meta name="description" content="Usaremos la función cpt.mean para detectar cambios significativos en la media de la serie. No se detectaron puntos de cambio, debido a que después de la diferenciación, se convierte básicamente en...">
<meta name="generator" content="bookdown 0.41 with bs4_book()">
<meta property="og:title" content="Chapter 5 Detección de Puntos de Cambio | EUR/USD">
<meta property="og:type" content="book">
<meta property="og:description" content="Usaremos la función cpt.mean para detectar cambios significativos en la media de la serie. No se detectaron puntos de cambio, debido a que después de la diferenciación, se convierte básicamente en...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 5 Detección de Puntos de Cambio | EUR/USD">
<meta name="twitter:description" content="Usaremos la función cpt.mean para detectar cambios significativos en la media de la serie. No se detectaron puntos de cambio, debido a que después de la diferenciación, se convierte básicamente en...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.8.0/transition.js"></script><script src="libs/bs3compat-0.8.0/tabs.js"></script><script src="libs/bs3compat-0.8.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">EUR/USD</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Justificación de elección del Dataset</a></li>
<li><a class="" href="intro.html"><span class="header-section-number">2</span> Estructura de los datos</a></li>
<li><a class="" href="preprocesamiento-y-visualizaci%C3%B3n.html"><span class="header-section-number">3</span> Preprocesamiento y Visualización</a></li>
<li><a class="" href="modelo-arima.html"><span class="header-section-number">4</span> Modelo ARIMA</a></li>
<li><a class="active" href="detecci%C3%B3n-de-puntos-de-cambio.html"><span class="header-section-number">5</span> Detección de Puntos de Cambio</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="detección-de-puntos-de-cambio" class="section level1" number="5">
<h1>
<span class="header-section-number">5</span> Detección de Puntos de Cambio<a class="anchor" aria-label="anchor" href="#detecci%C3%B3n-de-puntos-de-cambio"><i class="fas fa-link"></i></a>
</h1>
<p>Usaremos la función <code>cpt.mean</code> para detectar cambios significativos en la media de la serie.</p>
<div class="inline-figure"><img src="bookdown_time_series_files/figure-html/change-point-1.png" width="672"></div>
<p>No se detectaron puntos de cambio, debido a que después de la diferenciación, se convierte básicamente en ruido blanco.</p>
<div id="media-cero-de-los-residuos" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> Media Cero de los Residuos<a class="anchor" aria-label="anchor" href="#media-cero-de-los-residuos"><i class="fas fa-link"></i></a>
</h2>
<p>Comprobamos si la media de los residuos es cero.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Prueba t en los residuos</span></span>
<span><span class="va">residuals_arima</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">forex_arima</span><span class="op">)</span></span>
<span><span class="va">t_test_residuals</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">residuals_arima</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">t_test_residuals</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  residuals_arima
## t = 0.073986, df = 28858, p-value = 0.941
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -3.326619e-05  3.587612e-05
## sample estimates:
##    mean of x 
## 1.304966e-06</code></pre>
<p>La prueba t de una muestra realizada sobre los residuos (residuals_arima) arroja un valor de 𝑡=0.073986 con 28,858 grados de libertad y un valor p de 0.941. Dado que el valor p es significativamente mayor a 0.05, no rechazamos la hipótesis nula de que la media de los residuos es igual a cero. Esto sugiere que los residuos no presentan un sesgo significativo. El intervalo de confianza del 95% para la media de los residuos y la media estimada muy cercana a cero es consistente con un modelo bien ajustado sin tendencia sistemática en los errores.</p>
</div>
<div id="independencia-de-los-residuos" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> Independencia de los Residuos<a class="anchor" aria-label="anchor" href="#independencia-de-los-residuos"><i class="fas fa-link"></i></a>
</h2>
<p>Evaluamos la independencia de los residuos usando la prueba de Ljung-Box.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Prueba de independencia</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/box.test.html">Box.test</a></span><span class="op">(</span><span class="va">residuals_arima</span>, lag <span class="op">=</span> <span class="fl">20</span>, type <span class="op">=</span> <span class="st">"Ljung-Box"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  Box-Ljung test
## 
## data:  residuals_arima
## X-squared = 30.772, df = 20, p-value = 0.05827</code></pre>
<p>Los datos cargados contienen 28,860 filas y 6 columnas de información sobre el tipo de cambio EUR/USD. La prueba de Dickey-Fuller Aumentada (ADF) realizada en tres configuraciones (sin constante ni tendencia, con constante sin tendencia, y con constante y tendencia) muestra valores ADF altamente negativos y p-valores menores o iguales a 0.01, lo que indica que la serie diferenciada es estacionaria. Además, la prueba de Box-Ljung aplicada a los residuos del modelo ARIMA arroja un valor de 30.772 con un valor p de 0.05827, lo cual sugiere que los residuos <strong>no tienen autocorrelación significativa</strong>, indicando independencia en los errores del modelo.</p>
</div>
<div id="distribución-de-los-residuos" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> Distribución de los Residuos<a class="anchor" aria-label="anchor" href="#distribuci%C3%B3n-de-los-residuos"><i class="fas fa-link"></i></a>
</h2>
<p>Analizaremos la normalidad de los residuos con un gráfico Q-Q.</p>
<div class="inline-figure"><img src="bookdown_time_series_files/figure-html/residuals-qqplot-1.png" width="672"></div>
<p>El gráfico Q-Q muestra que los residuos del modelo se alinean con la normalidad en el centro de la distribución, pero presentan desviaciones significativas en las colas. Esto sugiere que, aunque los residuos se comportan aproximadamente como una distribución normal en el centro, tienen colas más pesadas de lo esperado, lo que indica la presencia de valores extremos.</p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="modelo-arima.html"><span class="header-section-number">4</span> Modelo ARIMA</a></div>
<div class="empty"></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#detecci%C3%B3n-de-puntos-de-cambio"><span class="header-section-number">5</span> Detección de Puntos de Cambio</a></li>
<li><a class="nav-link" href="#media-cero-de-los-residuos"><span class="header-section-number">5.1</span> Media Cero de los Residuos</a></li>
<li><a class="nav-link" href="#independencia-de-los-residuos"><span class="header-section-number">5.2</span> Independencia de los Residuos</a></li>
<li><a class="nav-link" href="#distribuci%C3%B3n-de-los-residuos"><span class="header-section-number">5.3</span> Distribución de los Residuos</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>EUR/USD</strong>" was written by Harvey Bastidas, Andrés Caicedo, Alexander Alvarado. It was last built on 2024-11-05.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
